In [3]:
!pip install pandas

In [4]:
import pandas as pd
import tensorflow as tf

In [13]:
data=pd.read_csv('housedata.csv')
data.head()

Unnamed: 0  MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  \
0           0           5         3         65.0     8450       1         3   
1           1           0         3         80.0     9600       1         3   
2           2           5         3         68.0    11250       1         0   
3           3           6         3         60.0     9550       1         0   
4           4           5         3         84.0    14260       1         0   

   1stFlrSF  2ndFlrSF  SalePrice  Total Years  
0       856       854     208500           17  
1      1262         0     181500           44  
2       920       866     223500           19  
3       961       756     140000          105  
4      1145      1053     250000           20

In [19]:
data.drop('Unnamed: 0',axis=1,inplace=True)

KeyError: "['Unnamed: 0'] not found in axis"

In [20]:
data.head()

MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  1stFlrSF  \
0           5         3         65.0     8450       1         3       856   
1           0         3         80.0     9600       1         3      1262   
2           5         3         68.0    11250       1         0       920   
3           6         3         60.0     9550       1         0       961   
4           5         3         84.0    14260       1         0      1145   

   2ndFlrSF  SalePrice  Total Years  
0       854     208500           17  
1         0     181500           44  
2       866     223500           19  
3       756     140000          105  
4      1053     250000           20

In [50]:
x=data.iloc[:,0:10]
x.drop('SalePrice',axis=1,inplace=True)

In [61]:
x=x.values

In [62]:
y=data.iloc[:,8:9].values
y

array([[208500],
       [181500],
       [223500],
       ...,
       [266500],
       [142125],
       [147500]], dtype=int64)

In [54]:
from sklearn.model_selection import train_test_split

In [63]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.25,random_state=None)

In [64]:
xtrain.shape


(900, 9)

In [65]:
xtest.shape

(301, 9)

In [66]:
classifier=tf.keras.models.Sequential()

In [87]:
classifier.add(tf.keras.layers.Flatten())
classifier.add(tf.keras.layers.Dense(units=256,activation='relu'))
classifier.add(tf.keras.layers.Dense(units=512,activation='relu'))
classifier.add(tf.keras.layers.Dense(units=1,activation='linear'))
classifier.compile(optimizer='adam',loss='mean_squared_error')

In [88]:
classifier.fit(xtrain,ytrain,batch_size=32,epochs=300)

Train on 900 samples
Epoch 1/300
900/900 [==============================] - 0s 542us/sample - loss: 6249886989.6533
Epoch 2/300
900/900 [==============================] - 0s 94us/sample - loss: 2443089706.3822
Epoch 3/300
900/900 [==============================] - 0s 95us/sample - loss: 2246772877.0844
Epoch 4/300
900/900 [==============================] - 0s 96us/sample - loss: 2375374235.8756
Epoch 5/300
900/900 [==============================] - 0s 116us/sample - loss: 2280005832.2489
Epoch 6/300
900/900 [==============================] - 0s 94us/sample - loss: 2203656941.2267
Epoch 7/300
900/900 [==============================] - 0s 100us/sample - loss: 2168537608.2489
Epoch 8/300
900/900 [==============================] - 0s 101us/sample - loss: 2149318152.1067
Epoch 9/300
900/900 [==============================] - 0s 93us/sample - loss: 2219373153.8489
Epoch 10/300
900/900 [==============================] - 0s 104us/sample - loss: 2281460865.7067
Epoch 11/300
900/900 [===========

900/900 [==============================] - 0s 130us/sample - loss: 2218738098.6311
Epoch 87/300
900/900 [==============================] - 0s 119us/sample - loss: 2057776725.9022
Epoch 88/300
900/900 [==============================] - 0s 102us/sample - loss: 2140513301.0489
Epoch 89/300
900/900 [==============================] - 0s 106us/sample - loss: 2066542205.1556
Epoch 90/300
900/900 [==============================] - 0s 103us/sample - loss: 2150890337.2800
Epoch 91/300
900/900 [==============================] - 0s 107us/sample - loss: 2113253911.6089
Epoch 92/300
900/900 [==============================] - 0s 114us/sample - loss: 2205860377.0311
Epoch 93/300
900/900 [==============================] - 0s 96us/sample - loss: 2072266065.7778
Epoch 94/300
900/900 [==============================] - 0s 89us/sample - loss: 2124590893.9378
Epoch 95/300
900/900 [==============================] - 0s 88us/sample - loss: 2211686448.0711
Epoch 96/300
900/900 [==============================] - 

900/900 [==============================] - 0s 102us/sample - loss: 2347573822.0089
Epoch 172/300
900/900 [==============================] - 0s 99us/sample - loss: 2273334313.5289
Epoch 173/300
900/900 [==============================] - 0s 89us/sample - loss: 2176017707.9467
Epoch 174/300
900/900 [==============================] - 0s 96us/sample - loss: 2078923293.0133
Epoch 175/300
900/900 [==============================] - 0s 96us/sample - loss: 2147947089.9200
Epoch 176/300
900/900 [==============================] - 0s 95us/sample - loss: 2007633824.4267
Epoch 177/300
900/900 [==============================] - 0s 100us/sample - loss: 2105875584.0000
Epoch 178/300
900/900 [==============================] - 0s 98us/sample - loss: 1982763229.2978
Epoch 179/300
900/900 [==============================] - 0s 96us/sample - loss: 2116114424.6044
Epoch 180/300
900/900 [==============================] - 0s 99us/sample - loss: 2191084620.2311
Epoch 181/300
900/900 [=============================

900/900 [==============================] - 0s 104us/sample - loss: 2042143091.2000
Epoch 256/300
900/900 [==============================] - 0s 99us/sample - loss: 2129537276.5867
Epoch 257/300
900/900 [==============================] - 0s 99us/sample - loss: 2229386886.8267
Epoch 258/300
900/900 [==============================] - 0s 100us/sample - loss: 2404339140.2667
Epoch 259/300
900/900 [==============================] - 0s 98us/sample - loss: 2125589661.5822
Epoch 260/300
900/900 [==============================] - 0s 101us/sample - loss: 2007258977.4933
Epoch 261/300
900/900 [==============================] - 0s 98us/sample - loss: 2043352545.2800
Epoch 262/300
900/900 [==============================] - 0s 100us/sample - loss: 1965662096.2133
Epoch 263/300
900/900 [==============================] - 0s 110us/sample - loss: 2178612009.5289
Epoch 264/300
900/900 [==============================] - 0s 96us/sample - loss: 2042952438.0444
Epoch 265/300
900/900 [==========================

In [89]:
classifier.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_2 (Flatten)          multiple                  0         
_________________________________________________________________
dense_4 (Dense)              multiple                  5120      
_________________________________________________________________
dense_5 (Dense)              multiple                  513       
_________________________________________________________________
flatten_3 (Flatten)          multiple                  0         
_________________________________________________________________
dense_6 (Dense)              multiple                  1024      
_________________________________________________________________
dense_7 (Dense)              multiple                  513       
_________________________________________________________________
flatten_4 (Flatten)          multiple                 

In [90]:
classifier.evaluate(xtest,ytest)

301/1 [=================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

1468068984.1328905

In [92]:
ypred=classifier.predict(xtest)
ypred

array([[192907.83 ],
       [243928.77 ],
       [191380.16 ],
       [161823.19 ],
       [172020.64 ],
       [257052.27 ],
       [114484.52 ],
       [124519.75 ],
       [342925.12 ],
       [327384.25 ],
       [136229.45 ],
       [ 85640.42 ],
       [228904.45 ],
       [277084.75 ],
       [214727.28 ],
       [242443.02 ],
       [294053.22 ],
       [225062.95 ],
       [ 36760.58 ],
       [103743.46 ],
       [160641.27 ],
       [134021.36 ],
       [128439.11 ],
       [290805.97 ],
       [102269.88 ],
       [233223.83 ],
       [233865.34 ],
       [311699.88 ],
       [253832.2  ],
       [164620.08 ],
       [122887.62 ],
       [106014.63 ],
       [149913.   ],
       [163150.19 ],
       [212227.64 ],
       [200716.08 ],
       [151321.31 ],
       [151721.75 ],
       [121062.07 ],
       [171638.47 ],
       [114170.195],
       [101112.07 ],
       [287184.16 ],
       [128924.43 ],
       [109297.96 ],
       [ 94751.164],
       [158189.03 ],
       [21355

In [91]:
from sklearn.metrics import r2_score
r2_score(ytest,ypred)

0.7798595639163953

In [103]:
classifier.predict([[0,3,80.0,9600,1,3,1262,0,44]])

array([[161214.44]], dtype=float32)